# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Sivamani K
first_name: Sivamani
middle_name: 
last_name: K
contact_note: >
  Feel free to reach out via email or connect with me on GitHub or LinkedIn.
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Computer Vision Engineer | Ph.D., Underwater Imaging | Project Associate @ SGBC, IIT Madras
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: computer vision, image processing, machine learning, AI, research, underwater imaging, GitHub portfolio
lang: en
icon: 📸

url: https://sivamani-k.github.io
baseurl: ""
last_updated: true
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# Contact Information
# -----------------------------------------------------------------------------
email: "sivamanik.44@gmail.com"
github_username: "sivamani-k"
linkedin_username: "sivamani-k-114b1897"
phone: "+91 8526662138"
location: "Chennai, TN, India"

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Sivamani's Blog
blog_description: Sharing my research and projects in computer vision and machine learning.
permalink: /blog/:year/:title/

pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Analytics and SEO
# -----------------------------------------------------------------------------
google_analytics: # Add your GA ID if you have one
google_site_verification: # Add your Google Search Console verification ID

# -----------------------------------------------------------------------------
# Open Graph & Social Sharing
# -----------------------------------------------------------------------------
serve_og_meta: true
serve_schema_org: true
og_image: /assets/img/profile.jpg # Replace with your profile picture path

# -----------------------------------------------------------------------------
# Projects Section
# -----------------------------------------------------------------------------
projects:
  - title: "DHARANI: A 3D Developing Human-brain Atlas"
    description: "Developed a production pipeline for 2D/3D image registration, multimodal imaging, and brain ATLAS creation."
    link: "https://brainportal.humanbrain.in/publicview/index.html"
  - title: "MAFFN_YOLOv5"
    description: "Proposed the Multi-Scale Attention Feature Fusion Network (MAFFN) for coral reef health detection."
    link: "https://github.com/sivamani-k/MAFFN_YOLOv5"
  - title: "3D Histological Cell Atlas"
    description: "Developed a 3D histological cell atlas using Gaussian Mixture Model, with GPU acceleration for enhanced processing."
    link: "https://github.com/sivamani-k"

# -----------------------------------------------------------------------------
# Publications Section
# -----------------------------------------------------------------------------
publications:
  - title: "MAFFN_YOLOv5: Multi-Scale Attention Feature Fusion Network on the YOLOv5 Model"
    journal: "Analytics, 2023"
    link: "https://doi.org/10.3390/analytics2010006"
  - title: "Multiscale decomposition and fusion-based color contrast restoration for various water-colored environments"
    journal: "Color Research and Application, 2022"
    link: "https://doi.org/10.1002/col.22728"
  - title: "DHARANI: A 3D Developing Human-brain Atlas Resource to Advance Neuroscience Internationally"
    journal: "Journal of Comparative Neurology (Accepted)"
    link: "https://brainportal.humanbrain.in/publicview/index.html"

# -----------------------------------------------------------------------------
# Skills
# -----------------------------------------------------------------------------
skills:
  - name: Programming Languages
    details: Python, MATLAB, C, C++, Assembly
  - name: Frameworks
    details: OpenCV, PyTorch, TensorFlow, NumPy, scikit-learn, CUDA, Docker
  - name: Computer Vision Techniques
    details: Image Registration, Reconstruction, Detection, Segmentation, Classification
  - name: Imaging Software
    details: FIJI, ITK-Snap, QuPath
  - name: DL Models
    details: YOLO, SAM, Detectron2, U-NET
  - name: Deployment Hardware
    details: NVIDIA Jetson Boards, FPGA, Raspberry Pi

# -----------------------------------------------------------------------------
# Certificates
# -----------------------------------------------------------------------------
certificates:
  - name: "Computer Vision Basics"
    issuer: "Coursera"
    link: "https://coursera.org/share/b9d45a1e18e6645105e20475d031e052"
  - name: "Deep Learning with PyTorch: Image Segmentation"
    issuer: "Coursera"
    link: "https://coursera.org/share/81af2b325fa61f1b418b45e49150a2c3"

# -----------------------------------------------------------------------------
# Contact Form
# -----------------------------------------------------------------------------
contact_form:
  enabled: true
  formspree_url: "https://formspree.io/f/{your_form_id}" # Replace with your Formspree endpoint





third_party_libraries:
  download: false
  bootstrap-table:
    version: "1.22.4"
    url:
      css: "https://cdn.jsdelivr.net/npm/bootstrap-table@1.22.4/dist/bootstrap-table.min.css"
      js: "https://cdn.jsdelivr.net/npm/bootstrap-table@1.22.4/dist/bootstrap-table.min.js"
  chartjs:
    version: "4.4.1"
    url:
      js: "https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"


 # - jekyll/scholar

 